# envoy v3 config.
admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 172.18.0.10
      port_value: 8001

static_resources:
  listeners:
  - name: listener_http
    address:
      socket_address:
        address: 172.18.0.10
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          http_protocol_options:
            accept_http_10: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "atai.com"
              routes:
              - match:
                  prefix: "/"
                redirect:
                  path_redirect: "/api/v1"
                  https_redirect: true
  - name: listener_https
    address:
      socket_address:
        address: 172.18.0.10
        port_value: 443
    listener_filters:
    - name: envoy.filters.listener.tls_inspector
      typed_config: {}
    filter_chains:
    - filter_chain_match:
        server_names:
        - atai.com
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: "/etc/envoy/certs/cert.pem"
              private_key:
                filename: "/etc/envoy/certs/key.pem"
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          use_remote_address: true
          http2_protocol_options:
            max_concurrent_streams: 100
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - atai.com
              routes:
              - match:
                  path: "/api/v1"
                route:
                  cluster: api_service
  clusters:
  - name: api_service
    connect_timeout: 15s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: local
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.18.0.11
                port_value: 443
